# Only postgres is supported ;)
[database]
host = "46.62.211.150"
port = 5432
user = "tas"
pass = "tas_password"
database = "tas_db"
timezone = "Europe/Berlin"

[server]
# The interface the server will listen on
host = "0.0.0.0"
# The port the server will listen on
port = 8000

[cors]
origins = [
  "http://localhost:5173",
  "http://localhost:8000",
  "https://tas.technulgy.com",
  "https://technulgy.com"
]

[auth]
# FusionAuth issuer, for example "https://auth.example.org".
issuer = "https://auth.tghd.eu"
client_id = ""
required_role = ""
# Keep false in production. True creates a local development admin without FusionAuth.
dev_allow_admin = true

[cloudflare]
images_account_id = "47765c1a6a9430ba1209e4f80255d9e6"
images_api_token = ""
# Example: "https://imagedelivery.net/<account_hash>"
images_delivery_url = "https://imagedelivery.net/j6Pc2fEGD4GrWGwEw45rRw/"
images_variant = "public"
