services:
  tas-backend:
    image: "ghcr.io/technulgy-lgnu/tas:${GIT_COMMIT_HASH:-latest}"
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_TIMEZONE=${DB_TIMEZONE}"
      - "EMAIL_HOST=${EMAIL_HOST}"
      - "EMAIL_SENDER_EMAIL=${EMAIL_SENDER_EMAIL}"
      - "EMAIL_PASSWORD=${EMAIL_PASSWORD}"
      - "DISCORD_WEBHOOK=${DISCORD_HOOK}"
      - "TDPUpload_Key=${TDPUpload_KEY}"
    networks:
      - traefik-nw
    restart: always
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:3001/healthcheck || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s

    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 2
      labels:
        - "traefik.enable=true"
        # Tas Backend
        - "traefik.http.routers.tas-backend.rule=Host(`api.tas.technulgy.com`)"
        - "traefik.http.routers.tas-backend.entrypoints=websecure"
        - "traefik.http.services.tas-backend.loadbalancer.server.port=3001"
        - "traefik.http.routers.tas-backend.tls=true"
        - "traefik.http.routers.tas-backend.tls.certresolver=cfACME"
        # Tas Links
        - "traefik.http.routers.tas-links.rule=Host(`links.technulgy.com`)"
        - "traefik.http.routers.tas-links.entrypoints=websecure"
        - "traefik.http.services.tas-links.loadbalancer.server.port=3002"
        - "traefik.http.routers.tas-links.tls=true"
        - "traefik.http.routers.tas-links.tls.certresolver=cfACME"

networks:
  traefik-nw:
    external: true
