# Only used for testing, so all will be pushed to git for ease of use

Database:
  Host: "192.168.178.137"
  Port: 5432
  Username: "tas"
  Password: "tasPassword"
  Database: "tas"
  TimeZone: "Europe/Berlin"

# This user will be deleted after the initial setup
User:
  InitialAdminUser: "admin@example.com"
  InitialAdminPassword: "adminPassword"

Website:
  Host: "0.0.0.0"
  Port: 8080

Email:
  Host: "mail.technulgy.com"
  ApiKey: "mhm"
  SenderEmail: "noreply@technulgy.com"
  Password: "2w@#i231&67D%9h$2T#6&z#cO@6@!!&0"

Nextcloud:
  Host: "nc.technulgy.com"
  ApiKey: "mhm"