name: compile-web
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  compileGo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.16
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Build
        run: go build -o rewriteFrontend ./util/main.go
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: rewriteFrontend

  rewriteFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rewriteFrontend
      - name: Run
        run: ./rewriteFrontend ../web
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: web

  compileWeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web
      - name: Run
        run: npm install
      - name: Run
        run: npm run build
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: web
